### ISSUE TITLE
Error encountered when running FFMExample

### ISSUE THREAD

**Issue by leoanghelescu** [Intel-bigdata/imllib-spark#11] opened 2017-08-23 00:56 UTC
Hello there,

Having a simple issue with running the example using my own sample data provided in this build.

I am using an EMR cluster and have run the following command and it seems to be accessing the code correctly and attempting to read the file:

_spark-shell --jars /home/hadoop/sepideh/imllib-spark/target/scala-2.11/imllib_2.11-0.0.1.jar -i ./FFMExample.scala bigdata.te.txt  2 3 0.01 0.00002 false false 2
[bigdata.te.txt](https://github.com/Intel-bigdata/imllib-spark/files/1243808/bigdata.te.txt)

Here is the issue I see when I run (this error occurs for every row in the training file):
<console>:1: error: ';' expected but integer literal found.
0 1000:977484:1.0000 2000:201926:1.0000 3000:0:1.0000 3001:0:1.0000 3002:0:1.0000 3003:0:1.0000 3004:0:1.0000 3005:0:1.0000 3006:0:1.0000 3007:1:1.0000 3008:0:1.0000 3009:0:1.0000 3010:0:1.0000 3011:0:1.0000 3012:0:1.0000 3013:0:1.0000 3014:0:1.0000 3015:0:1.0000 3016:0:1.0000 3017:0:1.0000 4000:0:1.0000 4001:0:1.0000 4002:0:1.0000 4003:0:1.0000 4004:0:1.0000 4005:0:1.0000 4006:0:1.0000 4007:0:1.0000 4008:0:1.0000 4009:0:1.0000 4010:0:1.0000 4011:0:1.0000 4012:0:1.0000 4013:0:1.0000 4014:0:1.0000 4015:0:1.0000 4016:0:1.0000 4017:0:1.0000 4018:0:1.0000 4019:0:1.0000 4020:0:1.0000 4021:0:1.0000 4022:0:1.0000 4023:0:1.0000 4024:0:1.0000 4025:0:1.0000 4026:0:1.0000 4027:0:1.0000 4028:0:1.0000 4029:0:1.0000 4030:0:1.0000 4031:0:1.0000 4032:0:1.0000 4033:0:1.0000 4034:0:1.0000 4035:0:1.0000 4036:0:1.0000 4037:0:1.0000 5000:0:1.0000
       ^
I have also tried the same with the example data "a9a_ffm" with the same issue.

Please let me know if you know what the issue may be. There are no semicolons in the either data file.

Thanks so much!
Leonard Anghelescu

**Comment by VinceShieh** [comment] 2017-08-23 06:36
Hi,
You should be able to run a9a_ffm successfully and we can not reproduce the issue on our end. I think the only difference is the environment that we run on.
Could you root cause the issue, whether the problem is in the data preprocessing or it's within the training step?

**Comment by VinceShieh** [comment] 2017-10-12 08:19
pls contact us if the problem still exists. Close the issue now

**Closed by VinceShieh** 2017-10-12 08:19 UTC
